version: '3.1'

services:
  shottron-db:
    image: postgres:${PSQL_TAG}
    restart: always
    ports:
      - 5332:5432
    volumes:
      -  ./mount/psql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PSQL_USER} -d ${PSQL_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

